// package transaction contains the logic for representing and moving assets on the network
package transaction

//internal/transaction/transaction.go
import (
	"crypto/sha256"
	"fmt"
	"log"
)

// Transaction represents an operation for transferring or registering assets
// It includes identification data, authorship, and the cryptographic signature
type Transaction struct {
	TXid         string // unique identifier generated by the transaction hash
	SenderID     string // address of the sender's wallet
	ReceiverID   string // address of the receiver's wallet
	AssetID      string // unique id of the asset (e.g., land plot or document)
	Action       string // type of operation (e.g., "transfer", "register")
	Fee          int64  // fee offered to miners for processing priority
	SenderPubKey []byte // sender's public key for signature verification
	Signature    []byte // digital signature proving the transaction's authenticity
}

// Serialize converts the transaction fields into a byte slice for hash generation.
// Note: we don't include TXid, SenderPubKey, or Signature here because 
// this is the exact raw data that the user originally signed.
func (tx Transaction) Serialize() []byte {
	return []byte(fmt.Sprintf("%s%s%s%s%d",
		tx.SenderID, tx.ReceiverID, tx.AssetID, tx.Action, tx.Fee))
}

// NewAndPostTransaction receives a FULLY FORMED transaction (already signed by the user)
// and attempts to validate and pool it.
func NewAndPostTransaction(
	m *Mempool,
	sender string,
	receiver string,
	asset string,
	action string,
	fee int64,
	senderPubKey []byte, 
	signature []byte,    
) *Transaction {

	// 1. Initialize the transaction with core business data and crypto proofs
	tx := &Transaction{
		SenderID:     sender,
		ReceiverID:   receiver,
		AssetID:      asset,
		Action:       action,
		Fee:          fee,
		SenderPubKey: senderPubKey,
		Signature:    signature,
	}

	// 2. Generate the TXid (the hash of the serialized data + signature)
	idData := append(tx.Serialize(), signature...)
	hash := sha256.Sum256(idData)
	tx.TXid = fmt.Sprintf("%x", hash)

	// 3. Validate mathematically and logically BEFORE putting in the mempool
	if !ValidateTransaction(*tx) {
		log.Printf("[TRANSACTION] Error: Transaction %s failed validation, rejected from mempool.", tx.TXid)
		return nil
	}

	// 4. Add to mempool (Assuming AddTransactionToMempool handles the locking)
	err := m.AddTransactionToMempool(*tx)
	if err != nil {
		log.Printf("[TRANSACTION] Error: failed to add %s to mempool: %v", tx.TXid, err)
		return nil
	}

	log.Printf("[TRANSACTION] New transaction validated and pooled: %s | Asset: %s", tx.TXid, tx.AssetID)
	return tx
}

// ValidateTransaction checks the integrity and authenticity of a transaction.
func ValidateTransaction(tx Transaction) bool {
	// 1. Check authenticity: is the signature valid for this sender's public key?
	isValidSignature := VerifySignature(tx.SenderPubKey, tx.Signature, tx.Serialize())
	if !isValidSignature {
		log.Printf("[TRANSACTION] Validation Error: Invalid signature for Asset %s", tx.AssetID)
		return false
	}

	// 2. Check business logic: are required fields present?
	if tx.AssetID == "" || tx.Action == "" || tx.SenderID == "" {
		log.Printf("[TRANSACTION] Validation Error: Missing critical fields")
		return false
	}

	// 3. Prevent spam: Ensure minimum fee or valid amounts (Example)
	if tx.Fee < 0 {
		log.Printf("[TRANSACTION] Validation Error: Negative fee not allowed")
		return false
	}

	return true
}